AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-lambda

  Sample SAM Template for java-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20


Resources:

  ItemsGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/distributions/app.zip
      Handler: com.antoinecampbell.cloud.springcloudfunction.Handler
      Runtime: java8
      Environment:
        Variables:
          FUNCTION_NAME: getItems
          SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.antoinecampbell.cloud.springcloudfunction
          SPRING_PROFILES_ACTIVE: lambda
      Events:
        GET:
          Type: Api
          Properties:
            Path: /items
            Method: GET

  ItemsCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/app.zip
      Handler: com.antoinecampbell.cloud.springcloudfunction.Handler
      Runtime: java8
      Environment:
        Variables:
          FUNCTION_NAME: createItem
          SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.antoinecampbell.cloud.springcloudfunction
          SPRING_PROFILES_ACTIVE: lambda
      Events:
        POST:
          Type: Api
          Properties:
            Path: /items
            Method: POST

  ItemsFindOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/app.zip
      Handler: com.antoinecampbell.cloud.springcloudfunction.Handler
      Runtime: java8
      Environment:
        Variables:
          FUNCTION_NAME: getItem
          SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.antoinecampbell.cloud.springcloudfunction
          SPRING_PROFILES_ACTIVE: lambda
      Events:
        POST:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: GET

  ItemsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/app.zip
      Handler: com.antoinecampbell.cloud.springcloudfunction.Handler
      Runtime: java8
      Environment:
        Variables:
          FUNCTION_NAME: updateItem
          SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.antoinecampbell.cloud.springcloudfunction
          SPRING_PROFILES_ACTIVE: lambda
      Events:
        POST:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: PUT

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
