spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: user
    initialization-mode: always

management:
  endpoint:
    mappings:
      enabled: true
---
spring:
  profiles: lambda

logging:
  level:
    root: OFF